# Generated by Django 2.1.5 on 2019-01-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20190113_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Insert Description Here.', max_length=500),
        ),
    ]
